Repository DD2480-Group-22/assignment-1, pull requests merged in 2020-01, with the labels that each got.

#4 Add maven config file
  pom.xml
Labels: enhancement

#8 Add general README
  README.md
Labels: documentation

#11 fix Removed comment from file
  .travis.yml
Labels: bug

#13 Add CodeCov to the repository
  .travis.yml
  README.md
  pom.xml
Labels: enhancement

#30 Revision Erik's code skeleton for the project
  pom.xml
  src/main/Main.java
  src/main/java/Main.java
  src/main/java/decide/Connectors.java
  src/main/java/decide/DecideHelpFunctions.java
  src/main/java/decide/DecideProgram.java
  src/main/java/decide/Parameters.java
  src/main/java/utilities/IOHandler.java
  src/main/resources/test_1.in
  src/test/java/decide/DecideHelpFunctionsTest.java
  src/test/java/decide/DecideProgramTest.java
  src/test/resources/test_1.in
Labels: documentation, enhancement

#38 fix/#36 Update Maven config
  pom.xml
Labels: bug, documentation

#39 feat/#29 Add the seventh condition function
  src/main/java/decide/DecideHelpFunctions.java
  src/test/java/decide/DecideHelpFunctionsTest.java
Labels: enhancement

#35 doc/#31 Add documentation for Maven and config file
  README.md
Labels: documentation

#57 feat/#52 Add Point2d library
  src/main/java/decide/DecideHelpFunctions.java
  src/main/java/decide/DecideProgram.java
  src/main/java/decide/Parameters.java
  src/test/java/decide/DecideHelpFunctionsTest.java
Labels: enhancement

#94 fix/#91 fixed LIC functions 8, 9 and 13, made the javadoc a little mo…
  src/main/java/decide/DecideHelpFunctions.java
  src/test/java/decide/DecideHelpFunctionsTest.java
Labels: bug
